from os import system
from tkinter import *
from tkinter import ttk
try:import pyautogui
except:
    system("pip install pyautogui")
    system("cls")
    import pyautogui

system("del answers_100.txt") ##If it is exist

root = Tk()

alto=600
ancho=1130

anchoalto=str(ancho-15)+"x"+str(alto)

root.geometry(anchoalto)
root.resizable(False,False)


main_frame = Frame(root,width=ancho,height=alto)
main_frame.place(x=0,y=0)

my_canvas = Canvas(main_frame, width=ancho, height=alto)
my_canvas.place(x=0,y=0)

my_scrollbar = ttk.Scrollbar(main_frame, orient=VERTICAL, command=my_canvas.yview)
my_scrollbar.place(x=1100,y=0,height=alto)

my_canvas.configure(yscrollcommand=my_scrollbar.set)
my_canvas.bind('<Configure>', lambda e: my_canvas.configure(scrollregion = my_canvas.bbox("all")))
def _on_mouse_wheel(event):
    my_canvas.yview_scroll(-1 * int((event.delta / 120)), "units")
my_canvas.bind_all("<MouseWheel>", _on_mouse_wheel)


second_frame = Frame(my_canvas,width=ancho,height=alto)
second_frame.place(x=0,y=0)
third_frame = Frame(width=500,height=500)
third_frame.place(x=500,y=50)


my_canvas.create_window((0,0), window=second_frame, anchor="nw")

A="A","a","1"
B="B","b","2"
C="C","c","3"
D="D","d","4"
E="E","e","5"

def myFunction(event=None):
    set_ans()



def key_handler(event=None):
    if event and event.keysym in (A+B+C+D+E):
        pyautogui.press("tab")
    if event.keysym=="BackSpace":
        pyautogui.hotkey('shift', 'tab')


root.bind('<Return>',myFunction)
root.bind('<Key>', key_handler)


def set_ans():
    with open("answers_100.txt", "a") as f:f.write(s1.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s2.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s3.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s4.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s5.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s6.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s7.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s8.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s9.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s10.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s11.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s12.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s13.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s14.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s15.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s16.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s17.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s18.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s19.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s20.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s21.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s22.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s23.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s24.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s25.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s26.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s27.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s28.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s29.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s30.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s31.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s32.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s33.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s34.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s35.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s36.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s37.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s38.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s39.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s40.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s41.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s42.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s43.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s44.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s45.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s46.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s47.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s48.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s49.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s50.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s51.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s52.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s53.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s54.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s55.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s56.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s57.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s58.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s59.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s60.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s61.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s62.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s63.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s64.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s65.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s66.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s67.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s68.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s69.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s70.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s71.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s72.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s73.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s74.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s75.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s76.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s77.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s78.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s79.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s80.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s81.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s82.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s83.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s84.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s85.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s86.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s87.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s88.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s89.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s90.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s91.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s92.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s93.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s94.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s95.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s96.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s97.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s98.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s99.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")
    with open("answers_100.txt", "a") as f:f.write(s100.get().replace("a","aA1").replace("A","aA1").replace("1","aA1").replace("b","bB2").replace("B","bB2").replace("2","bB2").replace("c","cC3").replace("C","cC3").replace("3","cC3").replace("d","dD4").replace("D","dD4").replace("4","dD4").replace("e","eE5").replace("E","eE5").replace("5","eE5")+" . \n")

    root.destroy()
    system("cls")
    system('"correction machine (100)GUI.py"')
set = Button(third_frame,text='set the ansewrs', font=("Roboto", 30),bg='green',fg="red",command=set_ans)
set.place(x=0,y=0)

Label(second_frame,text=1,font=("Roboto",25)).place(x=20,y=20)
s1=Entry(second_frame,width=2,font=('Arial 24'))
s1.place(x=100,y=20)
Label(second_frame,text=2,font=("Roboto",25)).place(x=20,y=70)
s2=Entry(second_frame,width=2,font=('Arial 24'))
s2.place(x=100,y=70)
Label(second_frame,text=3,font=("Roboto",25)).place(x=20,y=120)
s3=Entry(second_frame,width=2,font=('Arial 24'))
s3.place(x=100,y=120)
Label(second_frame,text=4,font=("Roboto",25)).place(x=20,y=170)
s4=Entry(second_frame,width=2,font=('Arial 24'))
s4.place(x=100,y=170)
Label(second_frame,text=5,font=("Roboto",25)).place(x=20,y=220)
s5=Entry(second_frame,width=2,font=('Arial 24'))
s5.place(x=100,y=220)
Label(second_frame,text=6,font=("Roboto",25)).place(x=20,y=270)
s6=Entry(second_frame,width=2,font=('Arial 24'))
s6.place(x=100,y=270)
Label(second_frame,text=7,font=("Roboto",25)).place(x=20,y=320)
s7=Entry(second_frame,width=2,font=('Arial 24'))
s7.place(x=100,y=320)
Label(second_frame,text=8,font=("Roboto",25)).place(x=20,y=370)
s8=Entry(second_frame,width=2,font=('Arial 24'))
s8.place(x=100,y=370)
Label(second_frame,text=9,font=("Roboto",25)).place(x=20,y=420)
s9=Entry(second_frame,width=2,font=('Arial 24'))
s9.place(x=100,y=420)
Label(second_frame,text=10,font=("Roboto",25)).place(x=20,y=470)
s10=Entry(second_frame,width=2,font=('Arial 24'))
s10.place(x=100,y=470)
Label(second_frame,text=11,font=("Roboto",25)).place(x=20,y=520)
s11=Entry(second_frame,width=2,font=('Arial 24'))
s11.place(x=100,y=520)
Label(second_frame,text=12,font=("Roboto",25)).place(x=20,y=570)
s12=Entry(second_frame,width=2,font=('Arial 24'))
s12.place(x=100,y=570)
Label(second_frame,text=13,font=("Roboto",25)).place(x=20,y=620)
s13=Entry(second_frame,width=2,font=('Arial 24'))
s13.place(x=100,y=620)
Label(second_frame,text=14,font=("Roboto",25)).place(x=20,y=670)
s14=Entry(second_frame,width=2,font=('Arial 24'))
s14.place(x=100,y=670)
Label(second_frame,text=15,font=("Roboto",25)).place(x=20,y=720)
s15=Entry(second_frame,width=2,font=('Arial 24'))
s15.place(x=100,y=720)
Label(second_frame,text=16,font=("Roboto",25)).place(x=20,y=770)
s16=Entry(second_frame,width=2,font=('Arial 24'))
s16.place(x=100,y=770)
Label(second_frame,text=17,font=("Roboto",25)).place(x=20,y=820)
s17=Entry(second_frame,width=2,font=('Arial 24'))
s17.place(x=100,y=820)
Label(second_frame,text=18,font=("Roboto",25)).place(x=20,y=870)
s18=Entry(second_frame,width=2,font=('Arial 24'))
s18.place(x=100,y=870)
Label(second_frame,text=19,font=("Roboto",25)).place(x=20,y=920)
s19=Entry(second_frame,width=2,font=('Arial 24'))
s19.place(x=100,y=920)
Label(second_frame,text=20,font=("Roboto",25)).place(x=20,y=970)
s20=Entry(second_frame,width=2,font=('Arial 24'))
s20.place(x=100,y=970)
Label(second_frame,text=21,font=("Roboto",25)).place(x=20,y=1020)
s21=Entry(second_frame,width=2,font=('Arial 24'))
s21.place(x=100,y=1020)
Label(second_frame,text=22,font=("Roboto",25)).place(x=20,y=1070)
s22=Entry(second_frame,width=2,font=('Arial 24'))
s22.place(x=100,y=1070)
Label(second_frame,text=23,font=("Roboto",25)).place(x=20,y=1120)
s23=Entry(second_frame,width=2,font=('Arial 24'))
s23.place(x=100,y=1120)
Label(second_frame,text=24,font=("Roboto",25)).place(x=20,y=1170)
s24=Entry(second_frame,width=2,font=('Arial 24'))
s24.place(x=100,y=1170)
Label(second_frame,text=25,font=("Roboto",25)).place(x=20,y=1220)
s25=Entry(second_frame,width=2,font=('Arial 24'))
s25.place(x=100,y=1220)
Label(second_frame,text=26,font=("Roboto",25)).place(x=20,y=1270)
s26=Entry(second_frame,width=2,font=('Arial 24'))
s26.place(x=100,y=1270)
Label(second_frame,text=27,font=("Roboto",25)).place(x=20,y=1320)
s27=Entry(second_frame,width=2,font=('Arial 24'))
s27.place(x=100,y=1320)
Label(second_frame,text=28,font=("Roboto",25)).place(x=20,y=1370)
s28=Entry(second_frame,width=2,font=('Arial 24'))
s28.place(x=100,y=1370)
Label(second_frame,text=29,font=("Roboto",25)).place(x=20,y=1420)
s29=Entry(second_frame,width=2,font=('Arial 24'))
s29.place(x=100,y=1420)
Label(second_frame,text=30,font=("Roboto",25)).place(x=20,y=1470)
s30=Entry(second_frame,width=2,font=('Arial 24'))
s30.place(x=100,y=1470)
Label(second_frame,text=31,font=("Roboto",25)).place(x=20,y=1520)
s31=Entry(second_frame,width=2,font=('Arial 24'))
s31.place(x=100,y=1520)
Label(second_frame,text=32,font=("Roboto",25)).place(x=20,y=1570)
s32=Entry(second_frame,width=2,font=('Arial 24'))
s32.place(x=100,y=1570)
Label(second_frame,text=33,font=("Roboto",25)).place(x=20,y=1620)
s33=Entry(second_frame,width=2,font=('Arial 24'))
s33.place(x=100,y=1620)
Label(second_frame,text=34,font=("Roboto",25)).place(x=20,y=1670)
s34=Entry(second_frame,width=2,font=('Arial 24'))
s34.place(x=100,y=1670)
Label(second_frame,text=35,font=("Roboto",25)).place(x=20,y=1720)
s35=Entry(second_frame,width=2,font=('Arial 24'))
s35.place(x=100,y=1720)
Label(second_frame,text=36,font=("Roboto",25)).place(x=20,y=1770)
s36=Entry(second_frame,width=2,font=('Arial 24'))
s36.place(x=100,y=1770)
Label(second_frame,text=37,font=("Roboto",25)).place(x=20,y=1820)
s37=Entry(second_frame,width=2,font=('Arial 24'))
s37.place(x=100,y=1820)
Label(second_frame,text=38,font=("Roboto",25)).place(x=20,y=1870)
s38=Entry(second_frame,width=2,font=('Arial 24'))
s38.place(x=100,y=1870)
Label(second_frame,text=39,font=("Roboto",25)).place(x=20,y=1920)
s39=Entry(second_frame,width=2,font=('Arial 24'))
s39.place(x=100,y=1920)
Label(second_frame,text=40,font=("Roboto",25)).place(x=20,y=1970)
s40=Entry(second_frame,width=2,font=('Arial 24'))
s40.place(x=100,y=1970)
Label(second_frame,text=41,font=("Roboto",25)).place(x=20,y=2020)
s41=Entry(second_frame,width=2,font=('Arial 24'))
s41.place(x=100,y=2020)
Label(second_frame,text=42,font=("Roboto",25)).place(x=20,y=2070)
s42=Entry(second_frame,width=2,font=('Arial 24'))
s42.place(x=100,y=2070)
Label(second_frame,text=43,font=("Roboto",25)).place(x=20,y=2120)
s43=Entry(second_frame,width=2,font=('Arial 24'))
s43.place(x=100,y=2120)
Label(second_frame,text=44,font=("Roboto",25)).place(x=20,y=2170)
s44=Entry(second_frame,width=2,font=('Arial 24'))
s44.place(x=100,y=2170)
Label(second_frame,text=45,font=("Roboto",25)).place(x=20,y=2220)
s45=Entry(second_frame,width=2,font=('Arial 24'))
s45.place(x=100,y=2220)
Label(second_frame,text=46,font=("Roboto",25)).place(x=20,y=2270)
s46=Entry(second_frame,width=2,font=('Arial 24'))
s46.place(x=100,y=2270)
Label(second_frame,text=47,font=("Roboto",25)).place(x=20,y=2320)
s47=Entry(second_frame,width=2,font=('Arial 24'))
s47.place(x=100,y=2320)
Label(second_frame,text=48,font=("Roboto",25)).place(x=20,y=2370)
s48=Entry(second_frame,width=2,font=('Arial 24'))
s48.place(x=100,y=2370)
Label(second_frame,text=49,font=("Roboto",25)).place(x=20,y=2420)
s49=Entry(second_frame,width=2,font=('Arial 24'))
s49.place(x=100,y=2420)
Label(second_frame,text=50,font=("Roboto",25)).place(x=20,y=2470)
s50=Entry(second_frame,width=2,font=('Arial 24'))
s50.place(x=100,y=2470)
Label(second_frame,text=51,font=("Roboto",25)).place(x=20,y=2520)
s51=Entry(second_frame,width=2,font=('Arial 24'))
s51.place(x=100,y=2520)
Label(second_frame,text=52,font=("Roboto",25)).place(x=20,y=2570)
s52=Entry(second_frame,width=2,font=('Arial 24'))
s52.place(x=100,y=2570)
Label(second_frame,text=53,font=("Roboto",25)).place(x=20,y=2620)
s53=Entry(second_frame,width=2,font=('Arial 24'))
s53.place(x=100,y=2620)
Label(second_frame,text=54,font=("Roboto",25)).place(x=20,y=2670)
s54=Entry(second_frame,width=2,font=('Arial 24'))
s54.place(x=100,y=2670)
Label(second_frame,text=55,font=("Roboto",25)).place(x=20,y=2720)
s55=Entry(second_frame,width=2,font=('Arial 24'))
s55.place(x=100,y=2720)
Label(second_frame,text=56,font=("Roboto",25)).place(x=20,y=2770)
s56=Entry(second_frame,width=2,font=('Arial 24'))
s56.place(x=100,y=2770)
Label(second_frame,text=57,font=("Roboto",25)).place(x=20,y=2820)
s57=Entry(second_frame,width=2,font=('Arial 24'))
s57.place(x=100,y=2820)
Label(second_frame,text=58,font=("Roboto",25)).place(x=20,y=2870)
s58=Entry(second_frame,width=2,font=('Arial 24'))
s58.place(x=100,y=2870)
Label(second_frame,text=59,font=("Roboto",25)).place(x=20,y=2920)
s59=Entry(second_frame,width=2,font=('Arial 24'))
s59.place(x=100,y=2920)
Label(second_frame,text=60,font=("Roboto",25)).place(x=20,y=2970)
s60=Entry(second_frame,width=2,font=('Arial 24'))
s60.place(x=100,y=2970)
Label(second_frame,text=61,font=("Roboto",25)).place(x=20,y=3020)
s61=Entry(second_frame,width=2,font=('Arial 24'))
s61.place(x=100,y=3020)
Label(second_frame,text=62,font=("Roboto",25)).place(x=20,y=3070)
s62=Entry(second_frame,width=2,font=('Arial 24'))
s62.place(x=100,y=3070)
Label(second_frame,text=63,font=("Roboto",25)).place(x=20,y=3120)
s63=Entry(second_frame,width=2,font=('Arial 24'))
s63.place(x=100,y=3120)
Label(second_frame,text=64,font=("Roboto",25)).place(x=20,y=3170)
s64=Entry(second_frame,width=2,font=('Arial 24'))
s64.place(x=100,y=3170)
Label(second_frame,text=65,font=("Roboto",25)).place(x=20,y=3220)
s65=Entry(second_frame,width=2,font=('Arial 24'))
s65.place(x=100,y=3220)
Label(second_frame,text=66,font=("Roboto",25)).place(x=20,y=3270)
s66=Entry(second_frame,width=2,font=('Arial 24'))
s66.place(x=100,y=3270)
Label(second_frame,text=67,font=("Roboto",25)).place(x=20,y=3320)
s67=Entry(second_frame,width=2,font=('Arial 24'))
s67.place(x=100,y=3320)
Label(second_frame,text=68,font=("Roboto",25)).place(x=20,y=3370)
s68=Entry(second_frame,width=2,font=('Arial 24'))
s68.place(x=100,y=3370)
Label(second_frame,text=69,font=("Roboto",25)).place(x=20,y=3420)
s69=Entry(second_frame,width=2,font=('Arial 24'))
s69.place(x=100,y=3420)
Label(second_frame,text=70,font=("Roboto",25)).place(x=20,y=3470)
s70=Entry(second_frame,width=2,font=('Arial 24'))
s70.place(x=100,y=3470)
Label(second_frame,text=71,font=("Roboto",25)).place(x=20,y=3520)
s71=Entry(second_frame,width=2,font=('Arial 24'))
s71.place(x=100,y=3520)
Label(second_frame,text=72,font=("Roboto",25)).place(x=20,y=3570)
s72=Entry(second_frame,width=2,font=('Arial 24'))
s72.place(x=100,y=3570)
Label(second_frame,text=73,font=("Roboto",25)).place(x=20,y=3620)
s73=Entry(second_frame,width=2,font=('Arial 24'))
s73.place(x=100,y=3620)
Label(second_frame,text=74,font=("Roboto",25)).place(x=20,y=3670)
s74=Entry(second_frame,width=2,font=('Arial 24'))
s74.place(x=100,y=3670)
Label(second_frame,text=75,font=("Roboto",25)).place(x=20,y=3720)
s75=Entry(second_frame,width=2,font=('Arial 24'))
s75.place(x=100,y=3720)
Label(second_frame,text=76,font=("Roboto",25)).place(x=20,y=3770)
s76=Entry(second_frame,width=2,font=('Arial 24'))
s76.place(x=100,y=3770)
Label(second_frame,text=77,font=("Roboto",25)).place(x=20,y=3820)
s77=Entry(second_frame,width=2,font=('Arial 24'))
s77.place(x=100,y=3820)
Label(second_frame,text=78,font=("Roboto",25)).place(x=20,y=3870)
s78=Entry(second_frame,width=2,font=('Arial 24'))
s78.place(x=100,y=3870)
Label(second_frame,text=79,font=("Roboto",25)).place(x=20,y=3920)
s79=Entry(second_frame,width=2,font=('Arial 24'))
s79.place(x=100,y=3920)
Label(second_frame,text=80,font=("Roboto",25)).place(x=20,y=3970)
s80=Entry(second_frame,width=2,font=('Arial 24'))
s80.place(x=100,y=3970)
Label(second_frame,text=81,font=("Roboto",25)).place(x=20,y=4020)
s81=Entry(second_frame,width=2,font=('Arial 24'))
s81.place(x=100,y=4020)
Label(second_frame,text=82,font=("Roboto",25)).place(x=20,y=4070)
s82=Entry(second_frame,width=2,font=('Arial 24'))
s82.place(x=100,y=4070)
Label(second_frame,text=83,font=("Roboto",25)).place(x=20,y=4120)
s83=Entry(second_frame,width=2,font=('Arial 24'))
s83.place(x=100,y=4120)
Label(second_frame,text=84,font=("Roboto",25)).place(x=20,y=4170)
s84=Entry(second_frame,width=2,font=('Arial 24'))
s84.place(x=100,y=4170)
Label(second_frame,text=85,font=("Roboto",25)).place(x=20,y=4220)
s85=Entry(second_frame,width=2,font=('Arial 24'))
s85.place(x=100,y=4220)
Label(second_frame,text=86,font=("Roboto",25)).place(x=20,y=4270)
s86=Entry(second_frame,width=2,font=('Arial 24'))
s86.place(x=100,y=4270)
Label(second_frame,text=87,font=("Roboto",25)).place(x=20,y=4320)
s87=Entry(second_frame,width=2,font=('Arial 24'))
s87.place(x=100,y=4320)
Label(second_frame,text=88,font=("Roboto",25)).place(x=20,y=4370)
s88=Entry(second_frame,width=2,font=('Arial 24'))
s88.place(x=100,y=4370)
Label(second_frame,text=89,font=("Roboto",25)).place(x=20,y=4420)
s89=Entry(second_frame,width=2,font=('Arial 24'))
s89.place(x=100,y=4420)
Label(second_frame,text=90,font=("Roboto",25)).place(x=20,y=4470)
s90=Entry(second_frame,width=2,font=('Arial 24'))
s90.place(x=100,y=4470)
Label(second_frame,text=91,font=("Roboto",25)).place(x=20,y=4520)
s91=Entry(second_frame,width=2,font=('Arial 24'))
s91.place(x=100,y=4520)
Label(second_frame,text=92,font=("Roboto",25)).place(x=20,y=4570)
s92=Entry(second_frame,width=2,font=('Arial 24'))
s92.place(x=100,y=4570)
Label(second_frame,text=93,font=("Roboto",25)).place(x=20,y=4620)
s93=Entry(second_frame,width=2,font=('Arial 24'))
s93.place(x=100,y=4620)
Label(second_frame,text=94,font=("Roboto",25)).place(x=20,y=4670)
s94=Entry(second_frame,width=2,font=('Arial 24'))
s94.place(x=100,y=4670)
Label(second_frame,text=95,font=("Roboto",25)).place(x=20,y=4720)
s95=Entry(second_frame,width=2,font=('Arial 24'))
s95.place(x=100,y=4720)
Label(second_frame,text=96,font=("Roboto",25)).place(x=20,y=4770)
s96=Entry(second_frame,width=2,font=('Arial 24'))
s96.place(x=100,y=4770)
Label(second_frame,text=97,font=("Roboto",25)).place(x=20,y=4820)
s97=Entry(second_frame,width=2,font=('Arial 24'))
s97.place(x=100,y=4820)
Label(second_frame,text=98,font=("Roboto",25)).place(x=20,y=4870)
s98=Entry(second_frame,width=2,font=('Arial 24'))
s98.place(x=100,y=4870)
Label(second_frame,text=99,font=("Roboto",25)).place(x=20,y=4920)
s99=Entry(second_frame,width=2,font=('Arial 24'))
s99.place(x=100,y=4920)
Label(second_frame,text=100,font=("Roboto",25)).place(x=20,y=4970)
s100=Entry(second_frame,width=2,font=('Arial 24'))
s100.place(x=100,y=4970)
second_frame.configure(height=5120.0)
root.mainloop()